language: python
python:
    - "3.4"
    - "3.5"

services:
    - docker

env:
    - MONGO=3.0 PYMONGO=">=2.8,<2.9"
    - MONGO=3.0 PYMONGO=">=2.9,<3.0"
    - MONGO=3.0 PYMONGO=">=3.0,<3.1"
    - MONGO=3.0 PYMONGO=">=3.1,<3.2"
    - MONGO=3.0 PYMONGO=">=3.2,<3.4"
    - MONGO=3.0 PYMONGO=">=3.4,<4"
    - MONGO=3.0 MOTOR=">=0.7,<1.0"

    - MONGO=3.2 PYMONGO=">=3.0,<3.1"
    - MONGO=3.2 PYMONGO=">=3.1,<3.2"
    - MONGO=3.2 PYMONGO=">=3.2,<3.4"
    - MONGO=3.2 PYMONGO=">=3.4,<4"
    - MONGO=3.2 MOTOR=">=1.0,<1.1"

    - MONGO=3.4 PYMONGO=">=3.1,<3.2"
    - MONGO=3.4 PYMONGO=">=3.2,<3.4"
    - MONGO=3.4 PYMONGO=">=3.4,<4"
    - MONGO=3.4 MOTOR=">=1.1,<2"

before_install:
    - docker run -d -p 127.0.0.1:27017:27017 mongo:$MONGO

install:
    - pip install -U pip
    - pip install -U pytest pytest-cov coveralls
    - test $PYMONGO && pip install pymongo$PYMONGO || true
    - test $MOTOR && pip install motor$MOTOR || true
    - python3 setup.py install

script:
    - py.test -v --cov yadm --cov-report term-missing

after_success:
    - coveralls
